### PR TITLE
Adding information about Netlify Forms in Jamstack documentation

### PR DESCRIPTION
**Pull request by SOYOO974**

### CODE REVIEW

**Review by eclipsesrl — COMMENTED** [review]
The text seems correct, just a little review for attributes, you should add this line of code 
`import Attribute from '@/components/Attribute.vue';`

on line 5

And on line 78 instead of  **data-netlify="true"**

use this

`<Attribute name="data-netlify" value="true" />`

in this way you can use our attribute element that has included a simple copy and paste. 
To preview the project you need to install NodeJs on your pc and run this command inside the folder:

`npm i && npm run develop`

**Comment by SOYOO974** [comment]
Updated to use the attribute element

**Comment by eclipsesrl** [comment]
> Hello, I updated to use the attribute element as suggested.
> 
> I didn't manage to preview the changes locally, I'm getting this error: https://prnt.sc/vghxv8
> It doesn't seem to find the image that I added when compiling. Can you please advise? Or is there a simpler way to preview the changes?
> 
> Thanks!

Seems the file is in the wrong path, add it to src/assets/images the path you used is just for static images outside the doc

**Comment by SOYOO974** [comment]
Thanks I will try to move the image in the src folder now and compile again

**Comment by SOYOO974** [comment]
OK everything seems good now, I think you can merge my branch with your master branch!
https://prnt.sc/vglrub

Just one comment about the Netlify documentation page, this H2 doesn't render correctly:
https://prnt.sc/vglsgl

**Pull request merged**
